/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import dynamic from 'next/dynamic';
import { useFrame } from '@react-three/fiber';


export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.gltf')


const mesh = useRef()
useFrame(()=>{

  if (mesh.current) {
    
    mesh.current.rotation.y += 0.005; // Rotate the model around the y-axis
  }
  
})



  return (
    <group ref={mesh} scale={[22,22,22]} {...props} dispose={null} >
      
      <mesh geometry={nodes.shoe.geometry}  material-color={'#A5DADD'} material={materials.laces}/>
       
     
      
      <mesh geometry={nodes.shoe_1.geometry} material-color={'#DCFFFE'}  material={materials.mesh}/>

      <mesh geometry={nodes.shoe_2.geometry} material-color={'#E3FFFF'} material={materials.caps} />
     
      <mesh geometry={nodes.shoe_3.geometry} material-color={'#E3FFFF'} material={materials.inner} />
     
      <mesh geometry={nodes.shoe_4.geometry} material-color={'#E3FFFF'}  material={materials.sole} />
    
      <mesh geometry={nodes.shoe_5.geometry} material-color={'#E3FFFF'} material={materials.stripes} />
    
      <mesh geometry={nodes.shoe_6.geometry} material-color={'#E3FFFF'} material={materials.band} />
     
      <mesh geometry={nodes.shoe_7.geometry} material-color={'#E3FFFF'} material={materials.patch} />
     
    </group>
  )
}

useGLTF.preload('/shoe.gltf')
